export interface Company {
  name: string;
  slug: string;
  logo: string;
  careers: string;
  applyLink: string;
  category: string;
  tags: string[];
  description: string;
  level: "Fresher" | "Experienced" | "Both";
}

export const companies: Company[] = [
  // ═══════════════════════════════════════════════════════════════════
  // FRESHER / ENTRY-LEVEL FRIENDLY (0-2 years experience)
  // Companies known to actively recruit fresh graduates
  // ═══════════════════════════════════════════════════════════════════

  // India Mass Recruiters
  { name: "TCS", slug: "tcs", logo: "https://www.google.com/s2/favicons?domain=tcs.com&sz=64", careers: "https://www.tcs.com/careers", applyLink: "https://www.tcs.com/careers/job-search", category: "India", tags: ["it-services", "outsourcing", "mass-recruiter", "new-grad", "india"], description: "Largest Indian IT employer — hires 100K+ freshers annually. TCS NQT is the campus exam.", level: "Fresher" },
  { name: "Infosys", slug: "infosys", logo: "https://www.google.com/s2/favicons?domain=infosys.com&sz=64", careers: "https://www.infosys.com/careers", applyLink: "https://www.infosys.com/careers/job-search.html", category: "India", tags: ["it-services", "outsourcing", "mass-recruiter", "new-grad", "india"], description: "Hires massive fresh batches. Infosys Springboard for free learning + hiring.", level: "Fresher" },
  { name: "Wipro", slug: "wipro", logo: "https://www.google.com/s2/favicons?domain=wipro.com&sz=64", careers: "https://www.wipro.com/careers", applyLink: "https://www.wipro.com/careers#open-positions", category: "India", tags: ["it-services", "cloud", "mass-recruiter", "new-grad", "india"], description: "Top campus recruiter — WILP program for freshers.", level: "Fresher" },
  { name: "HCLTech", slug: "hcltech", logo: "https://www.google.com/s2/favicons?domain=hcltech.com&sz=64", careers: "https://www.hcltech.com/careers", applyLink: "https://www.hcltech.com/careers#open-roles", category: "India", tags: ["it-services", "engineering", "mass-recruiter", "new-grad", "india"], description: "Major IT services employer — CodeSprint and campus hiring.", level: "Fresher" },
  { name: "Cognizant", slug: "cognizant", logo: "https://www.google.com/s2/favicons?domain=cognizant.com&sz=64", careers: "https://www.cognizant.com/careers", applyLink: "https://www.cognizant.com/us/en/careers/candidate-life-page", category: "India", tags: ["it-services", "digital", "mass-recruiter", "new-grad"], description: "Hires 30K+ freshers annually in India.", level: "Fresher" },
  { name: "Tech Mahindra", slug: "techmahindra", logo: "https://www.google.com/s2/favicons?domain=techmahindra.com&sz=64", careers: "https://www.techmahindra.com/careers", applyLink: "https://www.techmahindra.com/careers#open-positions", category: "India", tags: ["it-services", "telecom", "mass-recruiter", "new-grad", "india"], description: "Major IT services — strong campus hiring program.", level: "Fresher" },
  { name: "LTIMindtree", slug: "ltimindtree", logo: "https://www.google.com/s2/favicons?domain=ltimindtree.com&sz=64", careers: "https://www.ltimindtree.com/careers", applyLink: "https://www.ltimindtree.com/careers#openings", category: "India", tags: ["it-services", "new-grad", "india"], description: "L&T Infotech + Mindtree merger — active campus hiring.", level: "Fresher" },
  { name: "Mphasis", slug: "mphasis", logo: "https://www.google.com/s2/favicons?domain=mphasis.com&sz=64", careers: "https://www.mphasis.com/careers.html", applyLink: "https://www.mphasis.com/careers.html#current-openings", category: "India", tags: ["it-services", "new-grad", "india"], description: "IT services — regular freshers hiring drives.", level: "Fresher" },
  { name: "Hexaware", slug: "hexaware", logo: "https://www.google.com/s2/favicons?domain=hexaware.com&sz=64", careers: "https://www.hexaware.com/careers/", applyLink: "https://www.hexaware.com/careers/#openings", category: "India", tags: ["it-services", "automation", "new-grad", "india"], description: "IT services — campus hiring for freshers.", level: "Fresher" },

  // Global IT Services (Fresher Friendly)
  { name: "Accenture", slug: "accenture", logo: "https://www.google.com/s2/favicons?domain=accenture.com&sz=64", careers: "https://www.accenture.com/us-en/careers", applyLink: "https://www.accenture.com/us-en/careers/jobsearch", category: "Consulting", tags: ["consulting", "technology", "new-grad"], description: "Hires 100K+ freshers globally. Campus hiring + apprenticeships.", level: "Fresher" },
  { name: "Deloitte", slug: "deloitte", logo: "https://www.google.com/s2/favicons?domain=deloitte.com&sz=64", careers: "https://jobs.deloitte.com", applyLink: "https://jobs.deloitte.com/search", category: "Consulting", tags: ["consulting", "audit", "new-grad"], description: "Big 4 — strong campus hiring programs for new graduates.", level: "Fresher" },
  { name: "Capgemini", slug: "capgemini", logo: "https://www.google.com/s2/favicons?domain=capgemini.com&sz=64", careers: "https://www.capgemini.com/careers", applyLink: "https://www.capgemini.com/careers/job-offers/", category: "Consulting", tags: ["consulting", "it-services", "new-grad"], description: "Global IT services — massive fresher hiring in India.", level: "Fresher" },
  { name: "IBM", slug: "ibm", logo: "https://www.google.com/s2/favicons?domain=ibm.com&sz=64", careers: "https://www.ibm.com/careers", applyLink: "https://www.ibm.com/careers/search", category: "FAANG+", tags: ["cloud", "ai", "quantum", "new-grad", "apprenticeship"], description: "IBM SkillsBuild + apprenticeship programs for freshers.", level: "Both" },
  { name: "Atos", slug: "atos", logo: "https://www.google.com/s2/favicons?domain=atos.net&sz=64", careers: "https://www.atos.net/en/careers", applyLink: "https://www.atos.net/en/careers/join-us", category: "Consulting", tags: ["it-services", "new-grad"], description: "Global IT services — campus hiring programs.", level: "Fresher" },

  // FAANG+ New Grad Friendly
  { name: "Google", slug: "google", logo: "https://www.google.com/s2/favicons?domain=google.com&sz=64", careers: "https://careers.google.com", applyLink: "https://careers.google.com/jobs", category: "FAANG+", tags: ["search", "cloud", "ai", "new-grad"], description: "Search, Cloud, Android, YouTube, AI. New grad programs + GSoC.", level: "Both" },
  { name: "Microsoft", slug: "microsoft", logo: "https://www.google.com/s2/favicons?domain=microsoft.com&sz=64", careers: "https://careers.microsoft.com", applyLink: "https://gcsservices.careers.microsoft.com/search/results.html", category: "FAANG+", tags: ["cloud", "enterprise", "ai", "new-grad"], description: "Azure, Office, GitHub, LinkedIn, AI. Strong new grad pipeline.", level: "Both" },
  { name: "Amazon", slug: "amazon", logo: "https://www.google.com/s2/favicons?domain=amazon.com&sz=64", careers: "https://www.amazon.jobs", applyLink: "https://www.amazon.jobs/en/search?offset=0&result_limit=10&sort=relevant&category=software-development", category: "FAANG+", tags: ["cloud", "ecommerce", "ai", "new-grad"], description: "AWS, Prime, Alexa. New grad roles + return offer internship.", level: "Both" },
  { name: "Apple", slug: "apple", logo: "https://www.google.com/s2/favicons?domain=apple.com&sz=64", careers: "https://jobs.apple.com", applyLink: "https://jobs.apple.com/en/search#", category: "FAANG+", tags: ["hardware", "ios", "software", "new-grad"], description: "iOS, macOS, Hardware. University graduate programs.", level: "Both" },
  { name: "Meta", slug: "meta", logo: "https://www.google.com/s2/favicons?domain=meta.com&sz=64", careers: "https://www.metacareers.com", applyLink: "https://www.metacareers.com/jobs", category: "FAANG+", tags: ["social", "ai", "vr", "new-grad"], description: "Facebook, Instagram, WhatsApp. University recruiting.", level: "Both" },
  { name: "Netflix", slug: "netflix", logo: "https://www.google.com/s2/favicons?domain=netflix.com&sz=64", careers: "https://jobs.netflix.com", applyLink: "https://jobs.netflix.com/jobs", category: "FAANG+", tags: ["streaming", "content", "tech"], description: "Streaming, Content, Personalization.", level: "Experienced" },
  { name: "Oracle", slug: "oracle", logo: "https://www.google.com/s2/favicons?domain=oracle.com&sz=64", careers: "https://www.oracle.com/careers/", applyLink: "https://careers.oracle.com/jobs/#en/sites/jobsearch/requisitions", category: "FAANG+", tags: ["database", "cloud", "enterprise", "new-grad"], description: "Database, Cloud, Enterprise Software. Campus hiring.", level: "Both" },
  { name: "SAP", slug: "sap", logo: "https://www.google.com/s2/favicons?domain=sap.com&sz=64", careers: "https://www.sap.com/about/careers.html", applyLink: "https://jobs.sap.com/search/", category: "FAANG+", tags: ["erp", "enterprise", "cloud", "new-grad"], description: "Enterprise Software, ERP. Student ambassador + campus programs.", level: "Both" },
  { name: "Intel", slug: "intel", logo: "https://www.google.com/s2/favicons?domain=intel.com&sz=64", careers: "https://www.intel.com/content/www/us/en/jobs/jobs-at-intel.html", applyLink: "https://jobs.intel.com/en/search-jobs", category: "FAANG+", tags: ["hardware", "chips", "ai", "new-grad"], description: "Semiconductors, CPUs. Intern + new grad programs.", level: "Both" },
  { name: "Cisco", slug: "cisco", logo: "https://www.google.com/s2/favicons?domain=cisco.com&sz=64", careers: "https://jobs.cisco.com", applyLink: "https://jobs.cisco.com/jobs", category: "FAANG+", tags: ["networking", "security", "new-grad"], description: "Networking, Security. Campus hiring + early careers.", level: "Both" },

  // Startups & Mid-Size (Friendly to Freshers)
  { name: "Freshworks", slug: "freshworks", logo: "https://www.google.com/s2/favicons?domain=freshworks.com&sz=64", careers: "https://www.freshworks.com/careers", applyLink: "https://www.freshworks.com/careers#open-roles", category: "India", tags: ["saas", "crm", "new-grad", "india"], description: "SaaS, CRM, ITSM. Strong freshers hiring in Chennai.", level: "Fresher" },
  { name: "Zoho", slug: "zoho", logo: "https://www.google.com/s2/favicons?domain=zoho.com&sz=64", careers: "https://www.zoho.com/careers.html", applyLink: "https://www.zoho.com/careers.html#current-openings", category: "India", tags: ["saas", "enterprise", "new-grad", "india"], description: "SaaS Suite (45+ apps). Hires freshers directly — no agency.", level: "Fresher" },
  { name: "Razorpay", slug: "razorpay", logo: "https://www.google.com/s2/favicons?domain=razorpay.com&sz=64", careers: "https://razorpay.com/careers", applyLink: "https://razorpay.com/careers#open-positions", category: "India", tags: ["payments", "fintech", "new-grad", "india"], description: "Payments Platform — internship-to-FTE conversion.", level: "Both" },
  { name: "Meesho", slug: "meesho", logo: "https://www.google.com/s2/favicons?domain=meesho.com&sz=64", careers: "https://www.meesho.com/careers", applyLink: "https://www.meesho.com/careers#open-roles", category: "India", tags: ["ecommerce", "social", "new-grad", "india"], description: "Social Commerce — actively hiring fresh engineers.", level: "Both" },
  { name: "PhonePe", slug: "phonepe", logo: "https://www.google.com/s2/favicons?domain=phonepe.com&sz=64", careers: "https://www.phonepe.com/careers", applyLink: "https://www.phonepe.com/careers#open-positions", category: "India", tags: ["payments", "upi", "fintech", "new-grad", "india"], description: "UPI Payments — freshers + internship conversion.", level: "Both" },
  { name: "Groww", slug: "groww", logo: "https://www.google.com/s2/favicons?domain=groww.in&sz=64", careers: "https://groww.in/careers", applyLink: "https://groww.in/careers#openings", category: "India", tags: ["investing", "mutual-funds", "new-grad", "india"], description: "Investment Platform — startup culture, freshers welcome.", level: "Both" },
  { name: "CRED", slug: "cred", logo: "https://www.google.com/s2/favicons?domain=cred.club&sz=64", careers: "https://cred.club/careers", applyLink: "https://cred.club/careers#openings", category: "India", tags: ["fintech", "credit", "new-grad", "india"], description: "Credit Card Payments — hires top fresh talent.", level: "Both" },
  { name: "Zepto", slug: "zepto", logo: "https://www.google.com/s2/favicons?domain=zepto.com&sz=64", careers: "https://www.zepto.com/careers", applyLink: "https://www.zepto.com/careers#openings", category: "India", tags: ["quick-commerce", "new-grad", "india"], description: "Quick Commerce — fast-growing, hires fresh engineers.", level: "Both" },
  { name: "Swiggy", slug: "swiggy", logo: "https://www.google.com/s2/favicons?domain=swiggy.com&sz=64", careers: "https://careers.swiggy.com", applyLink: "https://careers.swiggy.com/jobs", category: "India", tags: ["food", "delivery", "new-grad", "india"], description: "Food Delivery, Instamart — campus + off-campus freshers.", level: "Both" },
  { name: "Zerodha", slug: "zerodha", logo: "https://www.google.com/s2/favicons?domain=zerodha.com&sz=64", careers: "https://zerodha.com/careers", applyLink: "https://zerodha.com/careers#open-roles", category: "India", tags: ["trading", "fintech", "new-grad", "india"], description: "Discount Brokerage — small team, freshers with strong skills.", level: "Both" },
  { name: "Sarvam AI", slug: "sarvam", logo: "https://www.google.com/s2/favicons?domain=sarvam.ai&sz=64", careers: "https://www.sarvam.ai/careers", applyLink: "https://www.sarvam.ai/careers", category: "India", tags: ["llm", "indian-languages", "ai", "new-grad", "india"], description: "India-Focused LLM Startup — AI freshers welcome.", level: "Both" },
  { name: "Flipkart", slug: "flipkart", logo: "https://www.google.com/s2/favicons?domain=flipkart.com&sz=64", careers: "https://www.flipkartcareers.com", applyLink: "https://www.flipkartcareers.com/job-search", category: "India", tags: ["ecommerce", "supply-chain", "new-grad", "india"], description: "E-commerce (Walmart India) — campus + lateral hiring.", level: "Both" },
  { name: "Tata Digital", slug: "tata-digital", logo: "https://www.google.com/s2/favicons?domain=tatadigital.com&sz=64", careers: "https://www.tatadigital.com/careers", applyLink: "https://www.tatadigital.com/careers#open-roles", category: "India", tags: ["super-app", "ecommerce", "new-grad", "india"], description: "Tata Neu Super App — freshers from top colleges.", level: "Both" },

  // Remote-First (Great for Freshers)
  { name: "GitLab", slug: "gitlab", logo: "https://www.google.com/s2/favicons?domain=gitlab.com&sz=64", careers: "https://about.gitlab.com/jobs", applyLink: "https://about.gitlab.com/jobs/#hiring", category: "DevTools", tags: ["devops", "ci/cd", "open-source", "remote", "new-grad"], description: "DevSecOps Platform — remote-first, async culture.", level: "Both" },
  { name: "Supabase", slug: "supabase", logo: "https://www.google.com/s2/favicons?domain=supabase.com&sz=64", careers: "https://supabase.com/careers", applyLink: "https://supabase.com/careers", category: "Cloud & Infra", tags: ["firebase-alternative", "postgres", "open-source", "remote", "new-grad"], description: "Open Source Firebase Alternative — remote team.", level: "Both" },
  { name: "Vercel", slug: "vercel", logo: "https://www.google.com/s2/favicons?domain=vercel.com&sz=64", careers: "https://vercel.com/careers", applyLink: "https://vercel.com/careers#open-roles", category: "Cloud & Infra", tags: ["frontend", "nextjs", "remote", "new-grad"], description: "Next.js, Frontend Cloud — remote-first team.", level: "Both" },
  { name: "DigitalOcean", slug: "digitalocean", logo: "https://www.google.com/s2/favicons?domain=digitalocean.com&sz=64", careers: "https://www.digitalocean.com/careers", applyLink: "https://www.digitalocean.com/careers#open-roles", category: "Cloud & Infra", tags: ["cloud", "devops", "remote", "new-grad"], description: "Developer Cloud — remote team.", level: "Both" },
  { name: "Notion", slug: "notion", logo: "https://www.google.com/s2/favicons?domain=notion.so&sz=64", careers: "https://www.notion.so/careers", applyLink: "https://www.notion.so/careers#openings", category: "DevTools", tags: ["productivity", "wiki", "new-grad"], description: "Connected Workspace — new grad roles available.", level: "Both" },
  { name: "Linear", slug: "linear", logo: "https://www.google.com/s2/favicons?domain=linear.app&sz=64", careers: "https://linear.app/careers", applyLink: "https://linear.app/careers", category: "DevTools", tags: ["project-management", "remote", "new-grad"], description: "Issue Tracking — small remote team.", level: "Both" },
  { name: "Postman", slug: "postman", logo: "https://www.google.com/s2/favicons?domain=postman.com&sz=64", careers: "https://www.postman.com/company/careers", applyLink: "https://www.postman.com/company/careers#open-roles", category: "DevTools", tags: ["api", "testing", "new-grad"], description: "API Development Platform — freshers + interns.", level: "Both" },
  { name: "Replit", slug: "replit", logo: "https://www.google.com/s2/favicons?domain=replit.com&sz=64", careers: "https://replit.com/careers", applyLink: "https://replit.com/careers", category: "DevTools", tags: ["ide", "cloud", "new-grad"], description: "Cloud IDE & AI Coding — startup, freshers welcome.", level: "Both" },

  // Open Source / Community (Great for Freshers)
  { name: "Hugging Face", slug: "huggingface", logo: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=64", careers: "https://huggingface.co/jobs", applyLink: "https://huggingface.co/jobs", category: "AI/ML", tags: ["open-source", "ml", "transformers", "new-grad"], description: "ML Platform, Open Source Models — community-driven.", level: "Both" },
  { name: "Cursor", slug: "cursor", logo: "https://www.google.com/s2/favicons?domain=cursor.com&sz=64", careers: "https://www.cursor.com/careers", applyLink: "https://www.cursor.com/careers", category: "AI/ML", tags: ["ai-editor", "ide", "new-grad"], description: "AI-First Code Editor — small team, high impact.", level: "Both" },

  // ═══════════════════════════════════════════════════════════════════
  // EXPERIENCED PROFESSIONALS (3+ years)
  // ═══════════════════════════════════════════════════════════════════

  // AI/ML (Senior Roles)
  { name: "OpenAI", slug: "openai", logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=64", careers: "https://openai.com/careers", applyLink: "https://boards.greenhouse.io/openai", category: "AI/ML", tags: ["llm", "research", "chatgpt", "senior"], description: "GPT, ChatGPT, DALL-E, Research. Primarily senior roles.", level: "Experienced" },
  { name: "Anthropic", slug: "anthropic", logo: "https://www.google.com/s2/favicons?domain=anthropic.com&sz=64", careers: "https://www.anthropic.com/careers", applyLink: "https://www.anthropic.com/careers#open-roles", category: "AI/ML", tags: ["llm", "safety", "claude", "senior"], description: "Claude, AI Safety Research. Senior research + engineering.", level: "Experienced" },
  { name: "DeepMind", slug: "deepmind", logo: "https://www.google.com/s2/favicons?domain=deepmind.com&sz=64", careers: "https://deepmind.google/about/careers", applyLink: "https://deepmind.google/about/careers/#open-roles", category: "AI/ML", tags: ["research", "agi", "senior"], description: "AI Research (Google). PhD-level research roles.", level: "Experienced" },
  { name: "Cohere", slug: "cohere", logo: "https://www.google.com/s2/favicons?domain=cohere.com&sz=64", careers: "https://cohere.com/careers", applyLink: "https://cohere.com/careers#open-roles", category: "AI/ML", tags: ["llm", "enterprise", "senior"], description: "Enterprise LLMs, NLP. Senior ML + engineering.", level: "Experienced" },
  { name: "Scale AI", slug: "scaleai", logo: "https://www.google.com/s2/favicons?domain=scale.com&sz=64", careers: "https://scale.com/careers", applyLink: "https://scale.com/careers#open-roles", category: "AI/ML", tags: ["data", "labeling", "defense", "senior"], description: "Data Platform, AI Infrastructure.", level: "Experienced" },
  { name: "Databricks", slug: "databricks", logo: "https://www.google.com/s2/favicons?domain=databricks.com&sz=64", careers: "https://www.databricks.com/company/careers", applyLink: "https://www.databricks.com/company/careers/open-positions", category: "AI/ML", tags: ["data", "lakehouse", "spark", "senior"], description: "Lakehouse, Spark, AI Platform. Senior data roles.", level: "Experienced" },
  { name: "Perplexity", slug: "perplexity", logo: "https://www.google.com/s2/favicons?domain=perplexity.ai&sz=64", careers: "https://perplexity.ai/careers", applyLink: "https://perplexity.ai/careers", category: "AI/ML", tags: ["search", "llm", "senior"], description: "AI Search Engine. Senior engineering roles.", level: "Experienced" },
  { name: "Mistral AI", slug: "mistral", logo: "https://www.google.com/s2/favicons?domain=mistral.ai&sz=64", careers: "https://mistral.ai/careers", applyLink: "https://mistral.ai/careers#open-positions", category: "AI/ML", tags: ["llm", "open-source", "europe", "senior"], description: "European LLM Company. Senior ML research.", level: "Experienced" },
  { name: "xAI", slug: "xai", logo: "https://www.google.com/s2/favicons?domain=x.ai&sz=64", careers: "https://x.ai/careers", applyLink: "https://x.ai/careers", category: "AI/ML", tags: ["llm", "grok", "senior"], description: "Grok, AI Research (Elon Musk). Senior roles.", level: "Experienced" },
  { name: "Groq", slug: "groq", logo: "https://www.google.com/s2/favicons?domain=groq.com&sz=64", careers: "https://groq.com/careers/", applyLink: "https://groq.com/careers/", category: "AI/ML", tags: ["inference", "lpu", "senior"], description: "Ultra-Fast AI Inference (LPU). Senior hardware + software.", level: "Experienced" },

  // Cloud & Infra (Senior Roles)
  { name: "Cloudflare", slug: "cloudflare", logo: "https://www.google.com/s2/favicons?domain=cloudflare.com&sz=64", careers: "https://www.cloudflare.com/careers", applyLink: "https://www.cloudflare.com/careers/jobs", category: "Cloud & Infra", tags: ["cdn", "security", "edge", "senior"], description: "CDN, Edge Computing, Security. Senior engineering.", level: "Experienced" },
  { name: "Fly.io", slug: "flyio", logo: "https://www.google.com/s2/favicons?domain=fly.io&sz=64", careers: "https://fly.io/jobs", applyLink: "https://fly.io/jobs#open-roles", category: "Cloud & Infra", tags: ["edge", "containers", "senior"], description: "Edge Containers, Global Deployments.", level: "Experienced" },
  { name: "Neon", slug: "neon", logo: "https://www.google.com/s2/favicons?domain=neon.tech&sz=64", careers: "https://neon.tech/careers", applyLink: "https://neon.tech/careers", category: "Cloud & Infra", tags: ["postgres", "serverless", "senior"], description: "Serverless Postgres. Senior database + systems.", level: "Experienced" },

  // SaaS / Enterprise (Senior Roles)
  { name: "Stripe", slug: "stripe", logo: "https://www.google.com/s2/favicons?domain=stripe.com&sz=64", careers: "https://stripe.com/jobs", applyLink: "https://stripe.com/jobs/search", category: "SaaS", tags: ["payments", "fintech", "api", "senior"], description: "Payments, Financial Infrastructure. Senior engineering.", level: "Experienced" },
  { name: "Shopify", slug: "shopify", logo: "https://www.google.com/s2/favicons?domain=shopify.com&sz=64", careers: "https://www.shopify.com/careers", applyLink: "https://www.shopify.com/careers/search", category: "SaaS", tags: ["ecommerce", "ruby", "rails", "senior"], description: "E-commerce Platform. Senior Ruby/Rails.", level: "Experienced" },
  { name: "Datadog", slug: "datadog", logo: "https://www.google.com/s2/favicons?domain=datadoghq.com&sz=64", careers: "https://www.datadoghq.com/careers", applyLink: "https://www.datadoghq.com/careers#open-positions", category: "SaaS", tags: ["monitoring", "observability", "senior"], description: "Monitoring, APM, Logs. Senior backend + infra.", level: "Experienced" },
  { name: "Grafana Labs", slug: "grafana", logo: "https://www.google.com/s2/favicons?domain=grafana.com&sz=64", careers: "https://grafana.com/company/careers", applyLink: "https://grafana.com/company/careers/#hiring", category: "SaaS", tags: ["monitoring", "open-source", "senior"], description: "Grafana, Loki, Tempo. Senior systems + Go.", level: "Experienced" },
  { name: "HashiCorp", slug: "hashicorp", logo: "https://www.google.com/s2/favicons?domain=hashicorp.com&sz=64", careers: "https://www.hashicorp.com/company/jobs", applyLink: "https://www.hashicorp.com/company/jobs#open-roles", category: "SaaS", tags: ["infra", "devops", "terraform", "senior"], description: "Terraform, Vault, Consul. Senior infra roles.", level: "Experienced" },
  { name: "MongoDB", slug: "mongodb", logo: "https://www.google.com/s2/favicons?domain=mongodb.com&sz=64", careers: "https://www.mongodb.com/careers", applyLink: "https://www.mongodb.com/careers#open-roles", category: "SaaS", tags: ["nosql", "database", "senior"], description: "Document Database, Atlas. Senior database roles.", level: "Experienced" },
  { name: "Snowflake", slug: "snowflake", logo: "https://www.google.com/s2/favicons?domain=snowflake.com&sz=64", careers: "https://careers.snowflake.com", applyLink: "https://careers.snowflake.com/us/en/search-results", category: "SaaS", tags: ["data-warehouse", "cloud", "senior"], description: "Cloud Data Warehouse. Senior data engineering.", level: "Experienced" },
  { name: "Elastic", slug: "elastic", logo: "https://www.google.com/s2/favicons?domain=elastic.co&sz=64", careers: "https://www.elastic.co/careers", applyLink: "https://www.elastic.co/careers#open-positions", category: "SaaS", tags: ["search", "analytics", "senior"], description: "Elasticsearch, Kibana. Senior search + distributed.", level: "Experienced" },

  // Security (Senior Roles)
  { name: "CrowdStrike", slug: "crowdstrike", logo: "https://www.google.com/s2/favicons?domain=crowdstrike.com&sz=64", careers: "https://www.crowdstrike.com/careers", applyLink: "https://www.crowdstrike.com/careers/search", category: "Security", tags: ["endpoint", "threat-intel", "senior"], description: "Endpoint Protection, Threat Intel. Senior security.", level: "Experienced" },
  { name: "Palo Alto Networks", slug: "paloaltonetworks", logo: "https://www.google.com/s2/favicons?domain=paloaltonetworks.com&sz=64", careers: "https://www.paloaltonetworks.com/careers", applyLink: "https://www.paloaltonetworks.com/careers#open-positions", category: "Security", tags: ["firewall", "cloud-security", "senior"], description: "Cybersecurity Platform. Senior security engineering.", level: "Experienced" },
  { name: "Wiz", slug: "wiz", logo: "https://www.google.com/s2/favicons?domain=wiz.io&sz=64", careers: "https://www.wiz.io/careers", applyLink: "https://www.wiz.io/careers#open-roles", category: "Security", tags: ["cloud-security", "cnapp", "senior"], description: "Cloud Security (CNAPP). Senior cloud + security.", level: "Experienced" },
  { name: "1Password", slug: "1password", logo: "https://www.google.com/s2/favicons?domain=1password.com&sz=64", careers: "https://1password.com/careers", applyLink: "https://1password.com/careers#open-roles", category: "Security", tags: ["password", "identity", "senior"], description: "Password Manager. Senior engineering.", level: "Experienced" },
  { name: "Snyk", slug: "snyk", logo: "https://www.google.com/s2/favicons?domain=snyk.io&sz=64", careers: "https://snyk.io/careers", applyLink: "https://snyk.io/careers#open-roles", category: "Security", tags: ["devsecops", "security", "senior"], description: "Developer Security. Senior security + Go.", level: "Experienced" },

  // Fintech (Senior Roles)
  { name: "PayPal", slug: "paypal", logo: "https://www.google.com/s2/favicons?domain=paypal.com&sz=64", careers: "https://careers.pypl.com", applyLink: "https://careers.pypl.com/search", category: "Fintech", tags: ["payments", "digital-wallet", "senior"], description: "Digital Payments. Senior engineering.", level: "Experienced" },
  { name: "Square (Block)", slug: "square", logo: "https://www.google.com/s2/favicons?domain=squareup.com&sz=64", careers: "https://squareup.com/us/en/careers", applyLink: "https://squareup.com/us/en/careers#open-roles", category: "Fintech", tags: ["payments", "pos", "senior"], description: "Payments, POS, Cash App. Senior roles.", level: "Experienced" },
  { name: "Plaid", slug: "plaid", logo: "https://www.google.com/s2/favicons?domain=plaid.com&sz=64", careers: "https://plaid.com/careers", applyLink: "https://plaid.com/careers#open-positions", category: "Fintech", tags: ["banking", "api", "senior"], description: "Financial Data API. Senior engineering.", level: "Experienced" },
  { name: "Robinhood", slug: "robinhood", logo: "https://www.google.com/s2/favicons?domain=robinhood.com&sz=64", careers: "https://robinhood.com/us/en/careers", applyLink: "https://robinhood.com/us/en/careers#open-roles", category: "Fintech", tags: ["trading", "investing", "senior"], description: "Commission-free Trading. Senior backend + mobile.", level: "Experienced" },
  { name: "Revolut", slug: "revolut", logo: "https://www.google.com/s2/favicons?domain=revolut.com&sz=64", careers: "https://www.revolut.com/careers", applyLink: "https://www.revolut.com/careers#open-roles", category: "Fintech", tags: ["neobank", "crypto", "senior"], description: "Neobank, Crypto, Europe. Senior engineering.", level: "Experienced" },
  { name: "Wise", slug: "wise", logo: "https://www.google.com/s2/favicons?domain=wise.com&sz=64", careers: "https://www.wise.jobs", applyLink: "https://www.wise.jobs/search", category: "Fintech", tags: ["remittance", "forex", "senior"], description: "International Money Transfer. Senior roles.", level: "Experienced" },
  { name: "Klarna", slug: "klarna", logo: "https://www.google.com/s2/favicons?domain=klarna.com&sz=64", careers: "https://www.klarna.com/careers/", applyLink: "https://www.klarna.com/careers/positions/", category: "Fintech", tags: ["bnpl", "payments", "senior"], description: "Buy Now, Pay Later. Senior engineering.", level: "Experienced" },
  { name: "Deel", slug: "deel", logo: "https://www.google.com/s2/favicons?domain=deel.com&sz=64", careers: "https://www.deel.com/careers", applyLink: "https://www.deel.com/careers#open-roles", category: "Fintech", tags: ["payroll", "global-hr", "senior"], description: "Global Payroll & HR. Senior roles.", level: "Experienced" },

  // Global Startups (Senior Roles)
  { name: "Spotify", slug: "spotify", logo: "https://www.google.com/s2/favicons?domain=spotify.com&sz=64", careers: "https://lifeatspotify.com", applyLink: "https://lifeatspotify.com/join-us", category: "Startups", tags: ["music", "streaming", "senior"], description: "Music & Podcasts Streaming. Senior backend + ML.", level: "Experienced" },
  { name: "Airbnb", slug: "airbnb", logo: "https://www.google.com/s2/favicons?domain=airbnb.com&sz=64", careers: "https://careers.airbnb.com", applyLink: "https://careers.airbnb.com/positions", category: "Startups", tags: ["travel", "marketplace", "senior"], description: "Travel Marketplace. Senior full-stack.", level: "Experienced" },
  { name: "Uber", slug: "uber", logo: "https://www.google.com/s2/favicons?domain=uber.com&sz=64", careers: "https://www.uber.com/careers", applyLink: "https://www.uber.com/global/en/careers", category: "Startups", tags: ["mobility", "delivery", "senior"], description: "Ride-sharing, Delivery, Freight. Senior engineering.", level: "Experienced" },
  { name: "Discord", slug: "discord", logo: "https://www.google.com/s2/favicons?domain=discord.com&sz=64", careers: "https://discord.com/careers", applyLink: "https://discord.com/careers#open-positions", category: "Startups", tags: ["chat", "gaming", "senior"], description: "Voice & Text Chat. Senior backend + infra.", level: "Experienced" },
  { name: "Duolingo", slug: "duolingo", logo: "https://www.google.com/s2/favicons?domain=duolingo.com&sz=64", careers: "https://careers.duolingo.com", applyLink: "https://careers.duolingo.com/jobs", category: "Startups", tags: ["edtech", "language", "ai", "senior"], description: "Language Learning. Senior ML + backend.", level: "Experienced" },
  { name: "Rippling", slug: "rippling", logo: "https://www.google.com/s2/favicons?domain=rippling.com&sz=64", careers: "https://www.rippling.com/careers", applyLink: "https://www.rippling.com/careers#open-roles", category: "Startups", tags: ["hr", "it", "payroll", "senior"], description: "HR, IT & Payroll Platform. Senior engineering.", level: "Experienced" },
  { name: "Coinbase", slug: "coinbase", logo: "https://www.google.com/s2/favicons?domain=coinbase.com&sz=64", careers: "https://www.coinbase.com/careers", applyLink: "https://www.coinbase.com/careers#openings", category: "Startups", tags: ["crypto", "exchange", "senior"], description: "Crypto Exchange. Senior blockchain + backend.", level: "Experienced" },

  // Robotics / Hardware (Senior Roles)
  { name: "Tesla", slug: "tesla", logo: "https://www.google.com/s2/favicons?domain=tesla.com&sz=64", careers: "https://www.tesla.com/careers", applyLink: "https://www.tesla.com/careers/search", category: "Robotics", tags: ["ev", "autonomous", "senior"], description: "EV, Autopilot, Energy. Senior engineering.", level: "Experienced" },
  { name: "NVIDIA", slug: "nvidia", logo: "https://www.google.com/s2/favicons?domain=nvidia.com&sz=64", careers: "https://nvidia.wd5.myworkdayjobs.com", applyLink: "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite", category: "Robotics", tags: ["gpu", "ai", "senior"], description: "GPU, AI Hardware, CUDA. Senior CUDA + ML.", level: "Experienced" },
  { name: "SpaceX", slug: "spacex", logo: "https://www.google.com/s2/favicons?domain=spacex.com&sz=64", careers: "https://www.spacex.com/careers/", applyLink: "https://www.spacex.com/careers/#positions", category: "Robotics", tags: ["rockets", "space", "senior"], description: "Rockets, Starlink, Space. Senior engineering.", level: "Experienced" },
  { name: "Waymo", slug: "waymo", logo: "https://www.google.com/s2/favicons?domain=waymo.com&sz=64", careers: "https://waymo.com/careers", applyLink: "https://waymo.com/careers#open-positions", category: "Robotics", tags: ["autonomous", "self-driving", "senior"], description: "Autonomous Vehicles. Senior perception + planning.", level: "Experienced" },
  { name: "Figure AI", slug: "figureai", logo: "https://www.google.com/s2/favicons?domain=figure.ai&sz=64", careers: "https://www.figure.ai/careers", applyLink: "https://www.figure.ai/careers", category: "Robotics", tags: ["humanoid", "ai", "senior"], description: "Humanoid Robots. Senior robotics + AI.", level: "Experienced" },

  // Gaming (Senior Roles)
  { name: "Epic Games", slug: "epicgames", logo: "https://www.google.com/s2/favicons?domain=epicgames.com&sz=64", careers: "https://www.epicgames.com/site/en-US/careers", applyLink: "https://www.epicgames.com/site/en-US/careers#jobs", category: "Gaming", tags: ["unreal", "fortnite", "senior"], description: "Unreal Engine, Fortnite. Senior game dev.", level: "Experienced" },
  { name: "Unity", slug: "unity", logo: "https://www.google.com/s2/favicons?domain=unity.com&sz=64", careers: "https://careers.unity.com", applyLink: "https://careers.unity.com/positions", category: "Gaming", tags: ["game-engine", "3d", "senior"], description: "Game Engine, 3D. Senior rendering + engine.", level: "Experienced" },
  { name: "Roblox", slug: "roblox", logo: "https://www.google.com/s2/favicons?domain=roblox.com&sz=64", careers: "https://corp.roblox.com/careers", applyLink: "https://corp.roblox.com/careers#open-roles", category: "Gaming", tags: ["metaverse", "social", "senior"], description: "Metaverse Platform. Senior infrastructure.", level: "Experienced" },
  { name: "Riot Games", slug: "riotgames", logo: "https://www.google.com/s2/favicons?domain=riotgames.com&sz=64", careers: "https://www.riotgames.com/careers", applyLink: "https://www.riotgames.com/en/work-with-us", category: "Gaming", tags: ["league", "valorant", "senior"], description: "League of Legends, Valorant. Senior game dev.", level: "Experienced" },
  { name: "Valve", slug: "valve", logo: "https://www.google.com/s2/favicons?domain=valvesoftware.com&sz=64", careers: "https://www.valvesoftware.com/jobs", applyLink: "https://www.valvesoftware.com/jobs#applying", category: "Gaming", tags: ["steam", "vr", "senior"], description: "Steam, VR, Games. Senior everything.", level: "Experienced" },

  // Media / Streaming
  { name: "Disney", slug: "disney", logo: "https://www.google.com/s2/favicons?domain=disney.com&sz=64", careers: "https://disneycareers.com", applyLink: "https://disneycareers.com/en/search-jobs", category: "Media", tags: ["streaming", "entertainment", "senior"], description: "Disney, Pixar, Marvel, Star Wars.", level: "Experienced" },
  { name: "Paramount", slug: "paramount", logo: "https://www.google.com/s2/favicons?domain=paramount.com&sz=64", careers: "https://www.paramount.com/careers", applyLink: "https://www.paramount.com/careers#open-roles", category: "Media", tags: ["streaming", "cbs", "senior"], description: "Paramount+, CBS, MTV.", level: "Experienced" },

  // Consulting
  { name: "McKinsey", slug: "mckinsey", logo: "https://www.google.com/s2/favicons?domain=mckinsey.com&sz=64", careers: "https://www.mckinsey.com/careers", applyLink: "https://www.mckinsey.com/careers/search-jobs", category: "Consulting", tags: ["strategy", "consulting", "senior"], description: "Strategy Consulting. Senior + MBA roles.", level: "Experienced" },
  { name: "BCG", slug: "bcg", logo: "https://www.google.com/s2/favicons?domain=bcg.com&sz=64", careers: "https://careers.bcg.com", applyLink: "https://careers.bcg.com/search-results", category: "Consulting", tags: ["strategy", "consulting", "senior"], description: "Boston Consulting Group. Senior + MBA roles.", level: "Experienced" },

  // International (Europe)
  { name: "Zalando (Berlin)", slug: "zalando", logo: "https://www.google.com/s2/favicons?domain=zalando.com&sz=64", careers: "https://jobs.zalando.com", applyLink: "https://jobs.zalando.com/#job-offers", category: "Europe", tags: ["ecommerce", "fashion", "senior"], description: "HQ: Berlin, Germany — Fashion E-commerce.", level: "Experienced" },
  { name: "N26 (Berlin)", slug: "n26", logo: "https://www.google.com/s2/favicons?domain=n26.com&sz=64", careers: "https://n26.com/careers", applyLink: "https://n26.com/careers#open-roles", category: "Europe", tags: ["neobank", "fintech", "senior"], description: "HQ: Berlin, Germany — Mobile Banking.", level: "Experienced" },
  { name: "Delivery Hero (Berlin)", slug: "deliveryhero", logo: "https://www.google.com/s2/favicons?domain=deliveryhero.com&sz=64", careers: "https://www.deliveryhero.com/careers", applyLink: "https://www.deliveryhero.com/careers#open-positions", category: "Europe", tags: ["food-delivery", "logistics", "senior"], description: "HQ: Berlin, Germany — Food Delivery.", level: "Experienced" },
  { name: "Contentful (Berlin)", slug: "contentful", logo: "https://www.google.com/s2/favicons?domain=contentful.com&sz=64", careers: "https://www.contentful.com/careers/", applyLink: "https://www.contentful.com/careers/#openings", category: "Europe", tags: ["cms", "developer-tools", "senior"], description: "HQ: Berlin, Germany — Headless CMS.", level: "Experienced" },
  { name: "SoundCloud (Berlin)", slug: "soundcloud", logo: "https://www.google.com/s2/favicons?domain=soundcloud.com&sz=64", careers: "https://soundcloud.com/careers", applyLink: "https://soundcloud.com/careers#open-roles", category: "Europe", tags: ["music", "audio", "senior"], description: "HQ: Berlin, Germany — Audio Platform.", level: "Experienced" },
  { name: "Bolt (Tallinn)", slug: "bolt", logo: "https://www.google.com/s2/favicons?domain=bolt.eu&sz=64", careers: "https://bolt.eu/en-us/careers", applyLink: "https://bolt.eu/en-us/careers/#open-roles", category: "Europe", tags: ["mobility", "delivery", "senior"], description: "HQ: Tallinn, Estonia — Ride-sharing.", level: "Experienced" },
  { name: "Wolt (Helsinki)", slug: "wolt", logo: "https://www.google.com/s2/favicons?domain=wolt.com&sz=64", careers: "https://wolt.com/en/careers", applyLink: "https://wolt.com/en/careers#open-roles", category: "Europe", tags: ["food-delivery", "senior"], description: "HQ: Helsinki, Finland — Food Delivery.", level: "Experienced" },

  // Asia-Pacific
  { name: "Grab (Singapore)", slug: "grab", logo: "https://www.google.com/s2/favicons?domain=grab.com&sz=64", careers: "https://grab.careers", applyLink: "https://grab.careers/#open-roles", category: "Asia-Pacific", tags: ["mobility", "delivery", "senior"], description: "HQ: Singapore — Super App.", level: "Experienced" },
  { name: "Gojek (Jakarta)", slug: "gojek", logo: "https://www.google.com/s2/favicons?domain=gojek.com&sz=64", careers: "https://www.gojek.com/careers/", applyLink: "https://www.gojek.com/careers/#openings", category: "Asia-Pacific", tags: ["mobility", "delivery", "senior"], description: "HQ: Jakarta, Indonesia — Super App.", level: "Experienced" },
  { name: "Sea Group / Shopee (Singapore)", slug: "sea", logo: "https://www.google.com/s2/favicons?domain=shopee.com&sz=64", careers: "https://careers.seagroup.com", applyLink: "https://careers.seagroup.com/#open-roles", category: "Asia-Pacific", tags: ["ecommerce", "gaming", "senior"], description: "HQ: Singapore — Shopee, Garena.", level: "Experienced" },
  { name: "Rakuten (Tokyo)", slug: "rakuten", logo: "https://www.google.com/s2/favicons?domain=rakuten.com&sz=64", careers: "https://rakuten.careers", applyLink: "https://rakuten.careers/#open-roles", category: "Asia-Pacific", tags: ["ecommerce", "fintech", "senior"], description: "HQ: Tokyo, Japan — E-commerce & Fintech.", level: "Experienced" },
  { name: "Tencent (Shenzhen)", slug: "tencent", logo: "https://www.google.com/s2/favicons?domain=tencent.com&sz=64", careers: "https://careers.tencent.com", applyLink: "https://careers.tencent.com/en-us/search.html", category: "Asia-Pacific", tags: ["gaming", "social", "senior"], description: "HQ: Shenzhen, China — WeChat, Gaming.", level: "Experienced" },
  { name: "Alibaba (Hangzhou)", slug: "alibaba", logo: "https://www.google.com/s2/favicons?domain=alibaba.com&sz=64", careers: "https://talent.alibaba.com", applyLink: "https://talent.alibaba.com/off-campus/position-list?lang=en", category: "Asia-Pacific", tags: ["ecommerce", "cloud", "senior"], description: "HQ: Hangzhou, China — E-commerce, Cloud.", level: "Experienced" },
  { name: "ByteDance (Beijing)", slug: "bytedance", logo: "https://www.google.com/s2/favicons?domain=bytedance.com&sz=64", careers: "https://jobs.bytedance.com", applyLink: "https://jobs.bytedance.com/en/position", category: "Asia-Pacific", tags: ["tiktok", "social", "ai", "senior"], description: "HQ: Beijing, China — TikTok, Lark.", level: "Experienced" },
  { name: "Samsung (Seoul)", slug: "samsung", logo: "https://www.google.com/s2/favicons?domain=samsung.com&sz=64", careers: "https://www.samsung.com/global/business/careers", applyLink: "https://www.samsung.com/global/business/careers/#open-roles", category: "Asia-Pacific", tags: ["hardware", "semiconductor", "senior"], description: "HQ: Seoul, South Korea — Electronics.", level: "Experienced" },

  // Middle East
  { name: "Careem (Dubai)", slug: "careem", logo: "https://www.google.com/s2/favicons?domain=careem.com&sz=64", careers: "https://www.careem.com/careers", applyLink: "https://www.careem.com/careers#open-roles", category: "Middle East", tags: ["mobility", "delivery", "senior"], description: "HQ: Dubai, UAE — Super App.", level: "Experienced" },
  { name: "Noon (Dubai)", slug: "noon", logo: "https://www.google.com/s2/favicons?domain=noon.com&sz=64", careers: "https://careers.noon.com", applyLink: "https://careers.noon.com/#open-positions", category: "Middle East", tags: ["ecommerce", "logistics", "senior"], description: "HQ: Dubai, UAE — E-commerce.", level: "Experienced" },

  // Africa
  { name: "Flutterwave (Lagos)", slug: "flutterwave", logo: "https://www.google.com/s2/favicons?domain=flutterwave.com&sz=64", careers: "https://www.flutterwave.com/careers", applyLink: "https://www.flutterwave.com/careers/#open-roles", category: "Africa", tags: ["fintech", "payments", "senior"], description: "HQ: Lagos, Nigeria — African Payments.", level: "Experienced" },
  { name: "Andela (Remote/Global)", slug: "andela", logo: "https://www.google.com/s2/favicons?domain=andela.com&sz=64", careers: "https://www.andela.com/careers", applyLink: "https://www.andela.com/careers/#open-roles", category: "Africa", tags: ["remote", "engineering", "senior"], description: "Remote-first — Global Engineering Talent.", level: "Both" },
  { name: "Paystack (Lagos)", slug: "paystack", logo: "https://www.google.com/s2/favicons?domain=paystack.com&sz=64", careers: "https://paystack.com/careers", applyLink: "https://paystack.com/careers#open-roles", category: "Africa", tags: ["fintech", "payments", "senior"], description: "HQ: Lagos, Nigeria — Payments (Stripe).", level: "Experienced" },
  { name: "Chipper Cash (Remote)", slug: "chippercash", logo: "https://www.google.com/s2/favicons?domain=chippercash.com&sz=64", careers: "https://chippercash.com/careers", applyLink: "https://chippercash.com/careers#openings", category: "Africa", tags: ["fintech", "payments", "senior"], description: "Pan-African Cross-border Payments.", level: "Experienced" },

  // Latin America
  { name: "Nubank (Sao Paulo)", slug: "nubank", logo: "https://www.google.com/s2/favicons?domain=nubank.com.br&sz=64", careers: "https://nubank.com.br/carreiras", applyLink: "https://nubank.com.br/carreiras#vagas", category: "Latin America", tags: ["neobank", "fintech", "senior"], description: "HQ: Sao Paulo, Brazil — Largest Neobank.", level: "Experienced" },
  { name: "MercadoLibre (Buenos Aires)", slug: "mercadolibre", logo: "https://www.google.com/s2/favicons?domain=mercadolibre.com&sz=64", careers: "https://mercadolibre.wd5.myworkdayjobs.com", applyLink: "https://mercadolibre.wd5.myworkdayjobs.com/mercadolibre", category: "Latin America", tags: ["ecommerce", "fintech", "senior"], description: "HQ: Buenos Aires, Argentina — LatAm E-commerce.", level: "Experienced" },
  { name: "Rappi (Bogota)", slug: "rappi", logo: "https://www.google.com/s2/favicons?domain=rappi.com&sz=64", careers: "https://rappi.com/careers", applyLink: "https://rappi.com/careers#open-roles", category: "Latin America", tags: ["delivery", "fintech", "senior"], description: "HQ: Bogota, Colombia — Delivery Super App.", level: "Experienced" },
  { name: "dLocal (Montevideo)", slug: "dlocal", logo: "https://www.google.com/s2/favicons?domain=dlocal.com&sz=64", careers: "https://www.dlocal.com/careers", applyLink: "https://www.dlocal.com/careers#open-roles", category: "Latin America", tags: ["payments", "cross-border", "senior"], description: "HQ: Montevideo, Uruguay — Cross-border Payments.", level: "Experienced" },
  { name: "Kavak (Mexico City)", slug: "kavak", logo: "https://www.google.com/s2/favicons?domain=kavak.com&sz=64", careers: "https://www.kavak.com/en/careers", applyLink: "https://www.kavak.com/en/careers#open-positions", category: "Latin America", tags: ["automotive", "ecommerce", "senior"], description: "HQ: Mexico City — Used Car Marketplace.", level: "Experienced" },
  { name: "Clip (Mexico City)", slug: "clip", logo: "https://www.google.com/s2/favicons?domain=clip.com&sz=64", careers: "https://clip.com/careers", applyLink: "https://clip.com/careers#open-roles", category: "Latin America", tags: ["payments", "fintech", "senior"], description: "HQ: Mexico City — Payments.", level: "Experienced" },
];

export function searchCompanies(query: string, category?: string, level?: string): Company[] {
  let results = companies;
  if (category) {
    results = results.filter((c) => c.category === category);
  }
  if (level && level !== "All") {
    results = results.filter((c) => c.level === level || c.level === "Both");
  }
  if (query) {
    const q = query.toLowerCase();
    results = results.filter(
      (c) =>
        c.name.toLowerCase().includes(q) ||
        c.category.toLowerCase().includes(q) ||
        c.tags.some((t) => t.includes(q)) ||
        c.description.toLowerCase().includes(q)
    );
  }
  return results;
}

export const categories = Array.from(new Set(companies.map((c) => c.category))).sort();
