services:
  - type: web
    name: cse-learner
    runtime: node
    repo: https://github.com/Knight-rule/cse-learner
    plan: free
    buildCommand: rm -rf .next && NEXT_PUBLIC_BUILD_ID=$(git rev-parse --short HEAD) pnpm build
    startCommand: pnpm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
